// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Amenity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("description");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("name");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("bytea")
                    .HasColumnName("row_version")
                    .HasDefaultValueSql("gen_random_bytes(8)");

                b.HasKey("Id")
                    .HasName("pk_amenities");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("ix_amenities_name");

                b.ToTable("amenities", null, t =>
                {
                    t.HasCheckConstraint("chk_amenities_description_length", "LENGTH(\"description\") >= 5");

                    t.HasCheckConstraint("chk_amenities_name_length", "LENGTH(\"name\") >= 2");
                });
            });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("DateAdded")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("date_added");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("end_date");

                b.Property<int>("ListingId")
                    .HasColumnType("integer")
                    .HasColumnName("listing_id");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("bytea")
                    .HasColumnName("row_version")
                    .HasDefaultValueSql("gen_random_bytes(8)");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("start_date");

                b.Property<int>("TenantId")
                    .HasColumnType("integer")
                    .HasColumnName("tenant_id");

                b.HasKey("Id")
                    .HasName("pk_bookings");

                b.HasIndex("ListingId")
                    .HasDatabaseName("ix_bookings_listing_id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_bookings_tenant_id");

                b.HasIndex("StartDate", "EndDate")
                    .HasDatabaseName("ix_bookings_start_date_end_date");

                b.ToTable("bookings", null, t =>
                {
                    t.HasCheckConstraint("chk_bookings_end_after_start", "\"end_date\" > \"start_date\"");
                });
            });

            modelBuilder.Entity("Domain.Entities.Listing", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasColumnName("currency");

                b.Property<DateTime>("DateAdded")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("date_added");

                b.Property<int>("MinRentalPeriodInMonths")
                    .HasColumnType("integer")
                    .HasColumnName("min_rental_period_in_months");

                b.Property<decimal>("Price")
                    .HasPrecision(10, 2)
                    .HasColumnType("numeric(10,2)")
                    .HasColumnName("price");

                b.Property<int>("PropertyId")
                    .HasColumnType("integer")
                    .HasColumnName("property_id");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("bytea")
                    .HasColumnName("row_version")
                    .HasDefaultValueSql("gen_random_bytes(8)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("status");

                b.HasKey("Id")
                    .HasName("pk_listings");

                b.HasIndex("PropertyId")
                    .HasDatabaseName("ix_listings_property_id");

                b.HasIndex("Status", "Price")
                    .HasDatabaseName("ix_listings_status_price");

                b.ToTable("listings", null, t =>
                {
                    t.HasCheckConstraint("chk_listings_min_period_positive", "\"min_rental_period_in_months\" > 0");

                    t.HasCheckConstraint("chk_listings_price_positive", "\"price\" > 0");
                });
            });

            modelBuilder.Entity("Domain.Entities.Property", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<string>("Location")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("location");

                b.Property<string>("PropertyType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("property_type");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("bytea")
                    .HasColumnName("row_version")
                    .HasDefaultValueSql("gen_random_bytes(8)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("title");

                b.Property<int>("UserId")
                    .HasColumnType("integer")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_properties");

                b.HasIndex("Location")
                    .HasDatabaseName("ix_properties_location");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_properties_user_id");

                b.ToTable("properties", null, t =>
                {
                    t.HasCheckConstraint("chk_properties_description_length", "LENGTH(\"description\") >= 10");

                    t.HasCheckConstraint("chk_properties_location_length", "LENGTH(\"location\") >= 5");

                    t.HasCheckConstraint("chk_properties_title_length", "LENGTH(\"title\") >= 5");
                });
            });

            modelBuilder.Entity("Domain.Entities.PropertyAmenity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("AmenityId")
                    .HasColumnType("integer")
                    .HasColumnName("amenity_id");

                b.Property<int>("PropertyId")
                    .HasColumnType("integer")
                    .HasColumnName("property_id");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("bytea")
                    .HasColumnName("row_version")
                    .HasDefaultValueSql("gen_random_bytes(8)");

                b.HasKey("Id")
                    .HasName("pk_property_amenities");

                b.HasIndex("AmenityId")
                    .HasDatabaseName("ix_property_amenities_amenity_id");

                b.HasIndex("PropertyId", "AmenityId")
                    .IsUnique()
                    .HasDatabaseName("ix_property_amenities_property_id_amenity_id");

                b.ToTable("property_amenities", (string)null);
            });

            modelBuilder.Entity("Domain.Entities.Review", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Comment")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("comment");

                b.Property<DateTime>("DateAdded")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("date_added");

                b.Property<int>("PropertyId")
                    .HasColumnType("integer")
                    .HasColumnName("property_id");

                b.Property<int>("Rating")
                    .HasColumnType("integer")
                    .HasColumnName("rating");

                b.Property<int>("ReviewerId")
                    .HasColumnType("integer")
                    .HasColumnName("reviewer_id");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("bytea")
                    .HasColumnName("row_version")
                    .HasDefaultValueSql("gen_random_bytes(8)");

                b.HasKey("Id")
                    .HasName("pk_reviews");

                b.HasIndex("PropertyId")
                    .HasDatabaseName("ix_reviews_property_id");

                b.HasIndex("Rating")
                    .HasDatabaseName("ix_reviews_rating");

                b.HasIndex("ReviewerId")
                    .HasDatabaseName("ix_reviews_reviewer_id");

                b.ToTable("reviews", null, t =>
                {
                    t.HasCheckConstraint("chk_reviews_comment_length", "LENGTH(\"comment\") >= 10");

                    t.HasCheckConstraint("chk_reviews_rating_range", "\"rating\" >= 1 AND \"rating\" <= 5");
                });
            });

            modelBuilder.Entity("Domain.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id")
                    .HasColumnOrder(0);

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("DateAdded")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("date_added");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("email");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("first_name");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("last_name");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("password_hash");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("bytea")
                    .HasColumnName("row_version")
                    .HasDefaultValueSql("gen_random_bytes(8)");

                b.HasKey("Id")
                    .HasName("pk_users");

                b.HasIndex("Email")
                    .IsUnique()
                    .HasDatabaseName("ix_users_email");

                b.ToTable("users", null, t =>
                {
                    t.HasCheckConstraint("chk_users_email_length", "LENGTH(\"email\") >= 7");

                    t.HasCheckConstraint("chk_users_first_name_length", "LENGTH(\"first_name\") >= 2");

                    t.HasCheckConstraint("chk_users_last_name_length", "LENGTH(\"last_name\") >= 2");

                    t.HasCheckConstraint("chk_users_password_hash_length", "LENGTH(\"password_hash\") >= 60");
                });
            });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
            {
                b.HasOne("Domain.Entities.Listing", "Listing")
                    .WithMany("Bookings")
                    .HasForeignKey("ListingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_bookings_listings_listing_id");

                b.HasOne("Domain.Entities.User", "Tenant")
                    .WithMany("Bookings")
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_bookings_users_tenant_id");

                b.Navigation("Listing");

                b.Navigation("Tenant");
            });

            modelBuilder.Entity("Domain.Entities.Listing", b =>
            {
                b.HasOne("Domain.Entities.Property", "Property")
                    .WithMany("Listings")
                    .HasForeignKey("PropertyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_listings_properties_property_id");

                b.Navigation("Property");
            });

            modelBuilder.Entity("Domain.Entities.Property", b =>
            {
                b.HasOne("Domain.Entities.User", "User")
                    .WithMany("Properties")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_properties_users_user_id");

                b.Navigation("User");
            });

            modelBuilder.Entity("Domain.Entities.PropertyAmenity", b =>
            {
                b.HasOne("Domain.Entities.Amenity", "Amenity")
                    .WithMany("PropertyAmenities")
                    .HasForeignKey("AmenityId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_property_amenities_amenities_amenity_id");

                b.HasOne("Domain.Entities.Property", "Property")
                    .WithMany("PropertyAmenities")
                    .HasForeignKey("PropertyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_property_amenities_properties_property_id");

                b.Navigation("Amenity");

                b.Navigation("Property");
            });

            modelBuilder.Entity("Domain.Entities.Review", b =>
            {
                b.HasOne("Domain.Entities.Property", "Property")
                    .WithMany("Reviews")
                    .HasForeignKey("PropertyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_reviews_properties_property_id");

                b.HasOne("Domain.Entities.User", "Reviewer")
                    .WithMany("Reviews")
                    .HasForeignKey("ReviewerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_reviews_users_reviewer_id");

                b.Navigation("Property");

                b.Navigation("Reviewer");
            });

            modelBuilder.Entity("Domain.Entities.Amenity", b =>
            {
                b.Navigation("PropertyAmenities");
            });

            modelBuilder.Entity("Domain.Entities.Listing", b =>
            {
                b.Navigation("Bookings");
            });

            modelBuilder.Entity("Domain.Entities.Property", b =>
            {
                b.Navigation("Listings");

                b.Navigation("PropertyAmenities");

                b.Navigation("Reviews");
            });

            modelBuilder.Entity("Domain.Entities.User", b =>
            {
                b.Navigation("Bookings");

                b.Navigation("Properties");

                b.Navigation("Reviews");
            });
#pragma warning restore 612, 618
        }
    }
}
